#!/bin/bash

# Help script for AlphaScrabble

echo "🎯 AlphaScrabble Help"
echo "===================="

echo ""
echo "📚 Overview"
echo "----------"
echo "AlphaScrabble is an AlphaZero-style Scrabble engine with:"
echo "  - Monte Carlo Tree Search (MCTS) with neural network guidance"
echo "  - GADDAG/DAWG lexicon for move generation"
echo "  - Self-play training pipeline"
echo "  - Interactive gameplay"
echo "  - Google Colab support"

echo ""
echo "🚀 Quick Start"
echo "-------------"
echo "1. Install: ./scripts/install.sh"
echo "2. Setup lexicon: ./scripts/setup_lexicon.sh"
echo "3. Run demo: ./scripts/run_demo.sh"
echo "4. Check status: ./scripts/status.sh"

echo ""
echo "📦 Installation"
echo "--------------"
echo "  ./scripts/install.sh          - Install AlphaScrabble"
echo "  ./scripts/dev_setup.sh        - Set up development environment"
echo "  ./scripts/setup_lexicon.sh    - Download and compile lexicon"
echo "  ./scripts/check_environment.sh - Check environment setup"

echo ""
echo "🧪 Testing & Development"
echo "-----------------------"
echo "  ./scripts/run_tests.sh        - Run test suite"
echo "  ./scripts/benchmark.sh        - Run performance benchmarks"
echo "  ./scripts/clean.sh            - Clean build artifacts"
echo "  ./scripts/status.sh           - Check system status"

echo ""
echo "🎮 Usage"
echo "-------"
echo "  alphascrabble --help                    - Show CLI help"
echo "  alphascrabble selfplay --games 10       - Generate training data"
echo "  alphascrabble train --data data/selfplay - Train model"
echo "  alphascrabble eval --net-a model.pt     - Evaluate model"
echo "  alphascrabble play --net model.pt       - Play interactively"

echo ""
echo "🎯 Demos"
echo "-------"
echo "  ./scripts/run_demo.sh all      - Run all demos"
echo "  ./scripts/run_demo.sh basic    - Basic component demo"
echo "  ./scripts/run_demo.sh quick    - Quick start demo"
echo "  ./scripts/run_demo.sh selfplay - Self-play demo"
echo "  ./scripts/run_demo.sh train    - Training demo"
echo "  ./scripts/run_demo.sh eval     - Evaluation demo"
echo "  ./scripts/run_demo.sh play     - Interactive play demo"

echo ""
echo "🔧 Maintenance"
echo "-------------"
echo "  ./scripts/backup.sh            - Create backup"
echo "  ./scripts/restore.sh <file>    - Restore from backup"
echo "  ./scripts/update.sh            - Update from git"
echo "  ./scripts/uninstall.sh         - Uninstall AlphaScrabble"

echo ""
echo "📁 Project Structure"
echo "-------------------"
echo "  alphascrabble/                 - Main package"
echo "    rules/                      - Scrabble rules and game logic"
echo "    engine/                     - MCTS, move generation, features"
echo "    nn/                         - Neural network models and training"
echo "    lexicon/                    - GADDAG/DAWG lexicon interface"
echo "    utils/                      - Utilities (logging, I/O, etc.)"
echo "    cli.py                      - Command-line interface"
echo "  cpp/                          - C++ wrapper for Quackle"
echo "  colab/                        - Google Colab notebook"
echo "  tests/                        - Test suite"
echo "  third_party/                  - Quackle source code"
echo "  lexica_cache/                 - Compiled lexicon files"

echo ""
echo "🔧 Configuration"
echo "---------------"
echo "  pyproject.toml                - Project configuration"
echo "  setup.py                      - Setup script"
echo "  requirements.txt              - Python dependencies"
echo "  Makefile                      - Build commands"
echo "  .github/workflows/            - CI/CD configuration"

echo ""
echo "📚 Documentation"
echo "---------------"
echo "  README.md                     - Main documentation"
echo "  colab/README.md               - Colab-specific docs"
echo "  scripts/README.md             - Scripts documentation"
echo "  colab/AlphaScrabble_Colab.ipynb - Interactive notebook"

echo ""
echo "🐛 Troubleshooting"
echo "-----------------"
echo "  ./scripts/check_environment.sh - Check environment"
echo "  ./scripts/status.sh           - Check system status"
echo "  ./scripts/clean.sh            - Clean build artifacts"
echo "  ./scripts/install.sh          - Reinstall AlphaScrabble"

echo ""
echo "💡 Tips"
echo "------"
echo "  - Use GPU for faster training and inference"
echo "  - Increase MCTS simulations for stronger play"
echo "  - Use larger batch sizes for faster training"
echo "  - Save checkpoints regularly during training"
echo "  - Use virtual environment for development"

echo ""
echo "🤝 Support"
echo "---------"
echo "  - GitHub Issues: https://github.com/alphascrabble/alphascrabble/issues"
echo "  - GitHub Discussions: https://github.com/alphascrabble/alphascrabble/discussions"
echo "  - Documentation: README.md"

echo ""
echo "📄 License"
echo "---------"
echo "  MIT License - see LICENSE file for details"

echo ""
echo "🎉 Happy Scrabble playing!"
