name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10, 3.11, 3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qtbase5-dev libqt5core5a build-essential cmake ninja-build
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -e ".[dev]"
    
    - name: Test with pytest
      run: |
        pytest tests/ -v --tb=short
    
    - name: Test basic imports
      run: |
        python -c "
        from alphascrabble.rules.board import Board
        from alphascrabble.rules.tiles_en import Tile, TileBag
        from alphascrabble.nn.model import AlphaScrabbleNet
        from alphascrabble.engine.features import FeatureExtractor
        print('✅ All imports successful')
        "
